---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tinkerbell.fullname" . | printf "%s-boots" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tinkerbell.labels" . | nindent 4 }}
    app.kubernetes.io/name: boots
    app.kubernetes.io/version: {{ .Values.boots.image.tag }}
spec:
  replicas: {{ .Values.boots.replicas }}
  selector:
    matchLabels:
      {{- include "tinkerbell.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: boots
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        ## TODO: I am familiar with K8S, but I have never seen this before,
        ## so I need to do some additional research. As far as I understand
        ## it, this is a way of assigning a specific IP of the host network
        ## to the pod.
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "interface": "net1",
              "ips": [
                "{{ .Values.boots.ip }}/{{ .Values.network.prefix }}"
              ],
              "name": "tink",
              "namespace": "{{ .Release.Namespace }}"
            }
          ]
        {{- with .Values.boots.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "tinkerbell.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: boots
    spec:
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tinkerbell.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.boots.podSecurityContext | nindent 8 }}
      initContainers:
        ## TODO: I am not sure what the interface name depends on here.
        ## My educated guess is that it refers to the WAN interface of
        ## the underlying Kubernetes node.
        - command: [ "/bin/sh", "-c", "iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE" ]
          image: docker.io/library/docker:dind
          name: gateway
          securityContext:
            capabilities:
              add: [ "NET_ADMIN", "NET_RAW" ]
            privileged: true
      containers:
        - name: boots
          args: [ "-log-level", "DEBUG" ]
          image: {{ printf "%s:%s" .Values.boots.image.repository (default "latest" .Values.boots.image.tag) }}
          imagePullPolicy: {{ .Values.boots.image.pullPolicy }}
          ## TODO: Remove secrets for container registry.
          ## TODO: Configure environment variables.
          # envFrom:
          #   - configMapRef:
          #       name: boots
          #   - secretRef:
          #       name: packet
          #   - secretRef:
          #       name: registry
          ## TODO: How do I configure the IPs for the other services,
          ## such as Nginx?
          env:
            - name: BOOTP_BIND
              value: 0.0.0.0:67
            - name: FACILITY_CODE
              value: "$(FACILITY)"
            - name: HTTP_BIND
              value: 0.0.0.0:80
            - name: SYSLOG_BIND
              value: 0.0.0.0:514
            - name: TFTP_BIND
              value: 0.0.0.0:69
          ports:
            - containerPort: 67
              name: dhcp
              protocol: UDP
            - containerPort: 69
              hostPort: 69
              name: tftp
              protocol: UDP
            - containerPort: 80
              hostPort: 80
              name: http
          ## TODO: Does boots have a health probe? If not,
          ## should we add a health probe to boots?
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          securityContext:
            {{- toYaml .Values.boots.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.boots.resources | nindent 12 }}
      {{- with .Values.boots.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.boots.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.boots.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tinkerbell.fullname" . | printf "%s-boots" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tinkerbell.labels" . | nindent 4 }}
    app.kubernetes.io/name: boots
    app.kubernetes.io/version: {{ .Values.boots.image.tag }}
spec:
  type: ClusterIP
  ports:
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: dhcp
    - name: tftp
      port: 69
      protocol: UDP
      targetPort: tftp
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "tinkerbell.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: boots
