---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dhcrelay
  name: dhcrelay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcrelay
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dhcrelay
    spec:
      containers:
        - args:
            - -id
            - $(IF_DOWNSTREAM)
            - -iu
            - $(IF_UPSTREAM)
            - boots
          envFrom:
            - configMapRef:
                name: dhcrelay
          image: docker.io/modem7/dhcprelay:latest
          imagePullPolicy: Always
          name: dhcrelay
          ports:
            - containerPort: 67
              hostPort: 67
              name: dhcp
              protocol: UDP
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhcrelay
  name: dhcrelay
spec:
  ports:
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: dhcp
  selector:
    app: dhcrelay
