---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tinkerbell.fullname" . | printf "%s-hegel" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tinkerbell.labels" . | nindent 4 }}
    app.kubernetes.io/name: hegel
    app.kubernetes.io/version: {{ .Values.hegel.image.tag }}
spec:
  replicas: {{ .Values.hegel.replicas }}
  selector:
    matchLabels:
      {{- include "tinkerbell.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: hegel
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.hegel.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tinkerbell.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: hegel
    spec:
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tinkerbell.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.boots.podSecurityContext | nindent 8 }}
      containers:
        - name: hegel
          args: [ "-log-level", "DEBUG" ]
          image: {{ printf "%s:%s" .Values.hegel.image.repository (default "latest" .Values.hegel.image.tag) }}
          imagePullPolicy: {{ .Values.hegel.image.pullPolicy }}
          ## TODO: Configure environment variables.
          # envFrom:
          #   - configMapRef:
          #       name: tink-client
          #   - secretRef:
          #       name: packet
          env:
            - name: GRPC_PORT
              value: "42115"
            - name: HEGEL_FACILITY
              value: "$(FACILITY)"
            - name: HEGEL_HTTP_PORT
              value: "50061"
            - name: HEGEL_USE_TLS
              value: "0"
          ports:
            - containerPort: 42115
              hostPort: 42115
              name: grpc
            - containerPort: 50061
              hostPort: 50061
              name: http
          securityContext:
            {{- toYaml .Values.hegel.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.hegel.resources | nindent 12 }}
      {{- with .Values.hegel.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hegel.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hegel.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tinkerbell.fullname" . | printf "%s-hegel" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tinkerbell.labels" . | nindent 4 }}
    app.kubernetes.io/name: hegel
    app.kubernetes.io/version: {{ .Values.hegel.image.tag }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 42115
      targetPort: grpc
    - name: http
      port: 50061
      targetPort: http
  selector:
    {{- include "tinkerbell.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: hegel
