---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "interface": "net1",
              "ips": [
                "192.168.1.3/29"
              ],
              "name": "tink",
              "namespace": "default"
            }
          ]
      labels:
        app: registry
    spec:
      containers:
        - env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:443
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
          image: docker.io/registry:2.7.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: 443
          name: registry
          ports:
            - containerPort: 443
              hostPort: 443
              name: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: 443
          volumeMounts:
            - mountPath: /auth
              name: registry-auth
            - mountPath: /certs
              name: certs
            - mountPath: /var/lib/registry
              name: registry-data
      initContainers:
        - command:
            - htpasswd
            - -Bbc
            - "$(REGISTRY_AUTH_HTPASSWD_PATH)"
            - "$(REGISTRY_USERNAME)"
            - "$(REGISTRY_PASSWORD)"
          envFrom:
            - secretRef:
                name: registry
          env:
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
          image: docker.io/registry:2.7.0
          imagePullPolicy: Always
          name: htpasswd
          volumeMounts:
            - mountPath: /auth
              name: registry-auth
      restartPolicy: Always
      volumes:
        - name: certs
          secret:
            secretName: certs
        - name: registry-auth
          emptyDir: {}
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
  name: registry-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
