---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tink-cli
  name: tink-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tink-cli
  template:
    metadata:
      labels:
        app: tink-cli
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: tink-client
          image: quay.io/tinkerbell/tink-cli:sha-0e8e5733
          imagePullPolicy: Always
          name: tink-cli
      restartPolicy: Always
